# kubectl apply -f k8s/secret.yaml
# kubectl get secrets

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque #그냥 일반적인 키-값 형태의 비밀 정보라는 뜻
stringData: #여기 적은 값은 K8s가 자동으로 base64 인코딩해서 저장
  POSTGRES_USER: app_user
  POSTGRES_PASSWORD: app_password
  POSTGRES_DB: ops_log